# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3fe459b037abe6a35686b4b95d51611ef538abf226ec13e506518707aa5a255c6295e53545c3fe90c916c02863e06369abdc7e11fbcfd393f0c66f2f1d0942c5

test:
  secret_key_base: db64258b394f60107c4bc1ccbeff7e32f390de365295355aae81ad6c22671a491d8e8de2a2527c8dd899921d7abcacecad11eeb6630e96cadafbb9f8326d3d2e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
